### ISSUE TITLE
Rtl support for floating label.

### ISSUE THREAD

**Issue by ghost** [FarbodSalamat-Zadeh/UsefulViews#12]
hello dear farbod.
how should i right align floating label for api lower than 17.
is it possible?

**Comment by farbodsz** [comment]
Unfortunately, at the moment, this is not possible, as it is something I had not considered when making `LabelledSpinner`.

However, I would agree that it is an important feature, so I will add it as a feature in the near future.

**Comment by ghost** [comment]
thank u so much

**Comment by farbodsz** [comment]
@besharati-behzad

If you just want to right-align, you can use the `android:gravity` attribute.

If you want to make it RTL (right-to-left, for Persian, Arabic, etc), you should be able to use the `android:textDirection` XML attribute for RTL text (see [here](http://stackoverflow.com/a/17221516/4230345)) and `android:layoutDirection` but for API 17 and above.

Unfortunately, there doesn't seem to be a way to implement this for below API 17, but let me know if this solves your issue...
