### ISSUE TITLE
Error text

### ISSUE THREAD

**Issue by farbodsz** [FarbodSalamat-Zadeh/UsefulViews#18]
Since @scottyab hasn't managed to open an issue for his comment on the original Gist file (what used to be a `LabelledSpinner.java` Gist), for reference purposes, here is what was mentioned::

> Thanks for this, it works well to show the hint. What would also be great is to show error text like the TextInputLayout. I might need that for current project, if so I'll see about contributing it back.

**Comment by farbodsz** [comment]
Again, for reference purposes, my comment (when this repo used to be just a Gist) was:

> Apologies for the late reply, scottyab - I have been working on making this an Android library.
> 
> Just to clarify, would you like the error text to be shown if the user makes an invalid selection (i.e. showing error text for specific selections)?
> 
> If so, in what way would you like it to be implemented? I have a suggestion below, but let me know if you have any other ideas:
> 
> ```
> int[] invalidSelectionIndices = {2, 4, 6, 7};
> String errorText = "This is a sample error text";
> labelledSpinner.setErrorSelection(invalidSelectionIndices, errorText);
> ```

**Comment by scottyab** [comment]
Hey @FarbodSalamat-Zadeh, great didn't know you'd promoted this to full repo, great! I figured the error text would appear similar to that of an edittext, as in `public void setError(CharSequence error)`. Not clear from a quick glance what invalidSelectionIndices are for?

**Comment by farbodsz** [comment]
Thanks, @scottyab - I should've let you know when I moved this to a full repo.

For the error text, we could use something like `setError(...)` , but since this would be with a Spinner, what selections would cause an error, and how would these be specified?

So `invalidSelectionIndices` would be an integer array of the indices of the items that you want to trigger an error. For example, in the case of my comment above, the 3rd, 5th, 7th and 8th items (because '0' would be the first item) would trigger the error message.

I hope this answers your question, but let me know what you think...

**Comment by scottyab** [comment]
Ok it I does answer my question, however I personally don't see the need to indicate which items are erroneous. It's a single option dropdown so as I see it the main use case for an error message is to say "Required, please select an item". But hey I guess if it supports that use case I'd be happy.

**Comment by farbodsz** [comment]
I didn't think of the error message being for the default Spinner item - so it would fit really nicely with what you mentioned in #19 .

I'll see if I can add in both of these, but if you want to make a pull request as well, feel free.

**Comment by farbodsz** [comment]
The sample app has not been properly updated to include the new features, but you can see the changes in the library files in the [commit I made today](https://github.com/FarbodSalamat-Zadeh/LabelledSpinner/commit/392ddfececac3b57601c92d9cf8776b2d5fbbea3).

**Comment by farbodsz** [comment]
@scottyab 
The sample app has now been updated, and you can access the new error text feature by updating your Gradle dependency to version 1.1.4.
Let me know if this solves your issue,

**Comment by scottyab** [comment]
@FarbodSalamat-Zadeh great, looks good!
