### ISSUE TITLE
Attribute "entries" conflicts with "entries" in com.android.support:preference-v* library

### ISSUE THREAD

**Issue by knagyorg** [FarbodSalamat-Zadeh/UsefulViews#32]
It's impossible to use this library with com.android.support:preference-v\* library because of conflict attribute name "entries". Please rename this attribute

**Comment by farbodsz** [comment]
Thanks for letting me know. This should be fixed by Thursday.

**Comment by farbodsz** [comment]
@knagyorg 

The issue has now been resolved  - thanks for informing me of it.

You can update the library dependency (of _UsefulViews_) to version 2.3.1.
The `entries` attribute of `LabelledSpinner` has been renamed to `spinnerEntries`.
