### ISSUE TITLE
Change floating label size

### ISSUE THREAD

**Issue by rubenfernandescabral** [FarbodSalamat-Zadeh/UsefulViews#39]
Is possible to change the floating label size? I think is to small.
Best Regards
Ruben Cabral

**Comment by farbodsz** [comment]
Hi Ruben. 

This has been on my to-do list for quite some time, but my laptop has encountered serious issues over the last month so I haven't been able to make improvements to any of my coding projects including this. 

Thannk you for your suggestion. I believe this has already been reported as well, so I'm closing it. See #38.
