### ISSUE TITLE
On Lollipop, text is not showing up

### ISSUE THREAD

**Issue by jorgeandresserrano** [FarbodSalamat-Zadeh/UsefulViews#40]
On Lollipop, text is not showing up. Probably it's a matter of colors, but how to control them? On Android 7, however, it does show properly.

app:widgetColor is set. Any clues?

![screen shot 2016-11-08 at 9 45 59 pm](https://cloud.githubusercontent.com/assets/2836809/20125663/e16073a6-a5fc-11e6-90d6-b2267606c8ee.png)

**Comment by farbodsz** [comment]
Thanks for reporting this. I'll investigate it, but my computer is not working at the moment so it may be a while until it's fixed.

**Comment by jorgeandresserrano** [comment]
I found out what the problem was. I was using the "wrong" `Context` to create the `ArrayAdapter`. This link may enlighten on the different types of `Context`s. [http://stackoverflow.com/questions/6854265/getapplicationcontext-getbasecontext-getapplication-getparent](url)

**Comment by farbodsz** [comment]
I'm glad you got it fixed :)
